package Main;
import java.util.*;
import Entidades.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.lang.*;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author FLIA HUDSON
 */
public class ABMSector extends javax.swing.JFrame {
    ControladorABMSector controladorABMSector = new ControladorABMSector();
    List<DTOSector> listaSectores;
    String nomfilSector;
    String codfilSector;
    javax.swing.table.DefaultTableModel miTabla=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Sector", "Nombre Sector", "Descripción", "Fecha Fin Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    
        /**
     * Creates new form ABMSector
     */
    public void setVisible(boolean b) {
        if (b==true) {
            List<DTOSector> listaSectores = controladorABMSector.buscarSectores();
            poblarTabla(listaSectores);
        }    
        super.setVisible(b);
        miTabla.getColumnClass(ICONIFIED);
    }     
    public void poblarTabla (List<DTOSector> listadtosectores){
        miTabla.setRowCount(0);
        for (int j=0;j<listadtosectores.size();j++)
        {
            DTOSector unSector = listadtosectores.get(j);   
            miTabla.addRow(new Object[]{unSector.getCodSector(),unSector.getNombreSector(),unSector.getDescripcionSector(),unSector.getFechaHoraFinVigenciaSector()});
        } 
        TablaSectores.setAutoCreateRowSorter(true);
        TablaSectores.setModel(miTabla);
    }
    public ABMSector() {
        initComponents();
        
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomSectorTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaSectores = new javax.swing.JTable();
        BotonAlta = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonMod = new javax.swing.JButton();
        codSectorTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Sector");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomSectorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomSectorTextFieldActionPerformed(evt);
            }
        });
        nomSectorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomSectorTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(nomSectorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 260, -1));

        TablaSectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Sector", "Nombre Sector", "Descripción", "Fin Vigencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaSectores.setRowHeight(20);
        TablaSectores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(TablaSectores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 460, 200));

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, -1));

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 60, -1));

        BotonMod.setText("Modificar");
        BotonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 120, -1));

        codSectorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codSectorTextFieldActionPerformed(evt);
            }
        });
        codSectorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codSectorTextFieldKeyReleased(evt);
            }
        });
        getContentPane().add(codSectorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 260, -1));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre Sector:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Código Sector:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, -1, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModActionPerformed
        Integer a;
        try  {
              a= (Integer) TablaSectores.getModel().getValueAt(TablaSectores.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Sector", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
       controladorABMSector.abrirModificar(cod,this);
      // System.out.print(cod);    
    }//GEN-LAST:event_BotonModActionPerformed

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        controladorABMSector.abrirAlta(this);
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        Integer a;
        try  {
              a= (Integer) TablaSectores.getModel().getValueAt(TablaSectores.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Sector", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
        controladorABMSector.abrirBaja(cod,this);
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void codSectorTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codSectorTextFieldKeyReleased
        if (!"".equals(codSectorTextField.getText())) try { 
            Integer a= Integer.parseInt(codSectorTextField.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese un número entero", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nomfilSector=nomSectorTextField.getText();
        codfilSector=codSectorTextField.getText();
        List<DTOSector> listaSectores = controladorABMSector.buscarSectores(nomfilSector,codfilSector);  
        poblarTabla(listaSectores);   
    }//GEN-LAST:event_codSectorTextFieldKeyReleased

    private void nomSectorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomSectorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomSectorTextFieldActionPerformed

    private void nomSectorTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomSectorTextFieldKeyReleased
        nomfilSector=nomSectorTextField.getText();
        codfilSector=codSectorTextField.getText();
        List<DTOSector> listaSectores = controladorABMSector.buscarSectores(nomfilSector,codfilSector);  
        poblarTabla(listaSectores);   
    }//GEN-LAST:event_nomSectorTextFieldKeyReleased

    private void codSectorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codSectorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codSectorTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMSector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonMod;
    private javax.swing.JTable TablaSectores;
    private javax.swing.JTextField codSectorTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomSectorTextField;
    // End of variables declaration//GEN-END:variables
}
