package Main;
import java.util.*;
import Entidades.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.lang.*;
/**
 *
 * @author FLIA HUDSON
 */
public class ABMSector extends javax.swing.JFrame {
    ControladorABMSector controladorABMSector = new ControladorABMSector();
    List<DTOSector> listaSectores;
    javax.swing.table.DefaultTableModel miTabla=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Sector", "Nombre Sector", "Descripción", "Fecha Fin Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        /**
     * Creates new form ABMSector
     */
    public void setVisible(boolean b) {
        if (b==true) {
            List<DTOSector> listaSectores = controladorABMSector.buscarSectores();
            for (int i=0;i<listaSectores.size();i++)
            {
                DTOSector unSector = listaSectores.get(i);
                miTabla.addRow(new Object[]{unSector.getCodSector(),unSector.getNombreSector(),unSector.getDescripcionSector(),unSector.getFechaHoraFinVigenciaSector()});
                TablaSectores.setModel(miTabla);
            }
        }
        super.setVisible(b); 
    }     
    public ABMSector() {
        initComponents();
        
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomSectorTextField = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        nomfilButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaSectores = new javax.swing.JTable();
        BotonAlta = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonMod = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        label2 = new java.awt.Label();
        codSectorTextField = new javax.swing.JTextField();
        codfilButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Sector");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nomSectorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, -1));

        label1.setText("Nombre Sector");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        nomfilButton.setText("Filtrar");
        nomfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nomfilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 80, -1));

        TablaSectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Sector", "Nombre Sector", "Descripción", "Fin Vigencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaSectores.setRowHeight(20);
        TablaSectores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(TablaSectores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 430, 200));

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, -1));

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, -1));

        BotonMod.setText("Modificar");
        BotonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 80, -1));

        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(actualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        label2.setText("Código Sector");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        getContentPane().add(codSectorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        codfilButton.setText("Filtrar");
        codfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codfilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(codfilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 80, -1));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfilButtonActionPerformed
        String nomfilSector;
        nomfilSector =nomSectorTextField.getText();
        //Limpio la tabla
        miTabla.setRowCount(0);
        List<DTOSector> listaSectores = controladorABMSector.buscarSectores(nomfilSector);  
        for (int j=0;j<listaSectores.size();j++)
        {
            DTOSector unSector = listaSectores.get(j);
            
            miTabla.addRow(new Object[]{unSector.getCodSector(),unSector.getNombreSector(),unSector.getDescripcionSector(),unSector.getFechaHoraFinVigenciaSector()});    
                        
                       
         } 
         TablaSectores.setModel(miTabla);
    }//GEN-LAST:event_nomfilButtonActionPerformed

    private void BotonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModActionPerformed
        Integer a;
        try  {
              a= (Integer) TablaSectores.getModel().getValueAt(TablaSectores.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Sector", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
       controladorABMSector.abrirModificar(cod);
      // System.out.print(cod);    
    }//GEN-LAST:event_BotonModActionPerformed

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        controladorABMSector.abrirAlta();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
       Integer a;
        try  {
              a= (Integer) TablaSectores.getModel().getValueAt(TablaSectores.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Sector", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
       controladorABMSector.abrirBaja(cod);
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        miTabla.setRowCount(0);
        setVisible(true);
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void codfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codfilButtonActionPerformed
        int codfilSector;
        if ("".equals(codSectorTextField.getText()) ){
            List<DTOSector> listaSectores = controladorABMSector.buscarSectores();
            miTabla.setRowCount(0);
               
          for (int j=0;j<listaSectores.size();j++)
        {
            DTOSector unSector = listaSectores.get(j);
            
            miTabla.addRow(new Object[]{unSector.getCodSector(),unSector.getNombreSector(),unSector.getDescripcionSector(),unSector.getFechaHoraFinVigenciaSector()});    
                        
                       
          }
          
         TablaSectores.setModel(miTabla);
         }
        else {
        codfilSector = Integer.parseInt(codSectorTextField.getText());
        //Limpio la tabla
        miTabla.setRowCount(0);
        List<DTOSector> listaSectores = controladorABMSector.buscarSectores(codfilSector);  
        
          for (int j=0;j<listaSectores.size();j++)
        {
            DTOSector unSector = listaSectores.get(j);
            
            miTabla.addRow(new Object[]{unSector.getCodSector(),unSector.getNombreSector(),unSector.getDescripcionSector(),unSector.getFechaHoraFinVigenciaSector()});    
                        
                       
          }
          
         TablaSectores.setModel(miTabla);
         }
    }//GEN-LAST:event_codfilButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMSector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonMod;
    private javax.swing.JTable TablaSectores;
    private javax.swing.JButton actualizarButton;
    private javax.swing.JTextField codSectorTextField;
    private javax.swing.JButton codfilButton;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField nomSectorTextField;
    private javax.swing.JButton nomfilButton;
    // End of variables declaration//GEN-END:variables
}
