package Main;
import java.util.*;
import Entidades.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.lang.*;
/**
 *
 * @author FLIA HUDSON
 */
public class ABMTipoTarea extends javax.swing.JFrame {
    ControladorABMTipoTarea controladorABMTipoTarea = new ControladorABMTipoTarea();
    List<DTOTipoTarea> listaTipoTareasVigentesOrdenada;
    String nomfilTipoTarea;
    String codfilTipoTarea;
    javax.swing.table.DefaultTableModel miTabla=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código TipoTarea", "Nombre TipoTarea", "Descripción", "Fecha Fin Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        /**
     * Creates new form TipoTarea
     */
    public void setVisible(boolean b) {
        if (b==true) {
            List<DTOTipoTarea> listaTipoTareas = controladorABMTipoTarea.buscarTipoTarea(nomfilTipoTarea=nomTipoTareaTextField.getText(),"");
            poblarTabla(listaTipoTareas);
            super.setVisible(b); 
        }
    }
    public void poblarTabla (List<DTOTipoTarea> listaTipoTareas){
        miTabla.setRowCount(0);
        listaTipoTareasVigentesOrdenada = ordenaTipoTarea(listaTipoTareas);
        for (int j=0;j<listaTipoTareasVigentesOrdenada.size();j++)
        {
            DTOTipoTarea unTipoTarea = listaTipoTareasVigentesOrdenada.get(j);   
            miTabla.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea(),unTipoTarea.getDescripcionTipoTarea(),unTipoTarea.getFechaFinVigenciaTipoTarea()});
        } 
        TablaTipoTarea.setModel(miTabla);
    }
    private  List<DTOTipoTarea> ordenaTipoTarea (List<DTOTipoTarea> listadtotipostarea)
    {
        List<DTOTipoTarea> ordenado,aux;
        ordenado=new ArrayList<DTOTipoTarea>();
        aux= new ArrayList<DTOTipoTarea>();
        for (int i=0; i< listadtotipostarea.size();i++)
        {
            aux.add(listadtotipostarea.get(i));
        }
        for (int i=0; i< listadtotipostarea.size();i++)
        {
            int ultCod=0;
            DTOTipoTarea saux=null;
            for(int j=0;j<aux.size();j++)
            {
                if(ultCod ==0)
                {
                    ultCod=aux.get(j).getCodTipoTarea();
                    saux=aux.get(j);
                }
                if (ultCod >aux.get(j).getCodTipoTarea())
                {
                    ultCod=aux.get(j).getCodTipoTarea();
                    saux=aux.get(j);
                }
            }
            ordenado.add(saux);
            aux.remove(saux);
        }
         return ordenado; 
    }
    public ABMTipoTarea() {
        initComponents();
        nomTipoTareaTextField.setText("");
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        nomTipoTareaTextField = new javax.swing.JTextField();
        BotonMod = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonAlta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTipoTarea = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM Tipo Tarea");

        label1.setText("Nombre Tipo Tarea");

        nomTipoTareaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomTipoTareaTextFieldKeyReleased(evt);
            }
        });

        BotonMod.setText("Modificar");
        BotonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModActionPerformed(evt);
            }
        });

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });

        TablaTipoTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código TipoTarea", "Nombre Tipo Tarea", "Descripción", "Fin Vigencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaTipoTarea.setRowHeight(20);
        TablaTipoTarea.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(TablaTipoTarea);
        if (TablaTipoTarea.getColumnModel().getColumnCount() > 0) {
            TablaTipoTarea.getColumnModel().getColumn(0).setMinWidth(0);
            TablaTipoTarea.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BotonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomTipoTareaTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomTipoTareaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAlta)
                            .addComponent(BotonBaja)
                            .addComponent(BotonMod)))
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModActionPerformed
        Integer a;
        try  {
            a= (Integer) TablaTipoTarea.getModel().getValueAt(TablaTipoTarea.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un TipoTarea", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
        controladorABMTipoTarea.abrirModificar(cod,this);
        // System.out.print(cod);
    }//GEN-LAST:event_BotonModActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        Integer a;
        try  {
            a= (Integer) TablaTipoTarea.getModel().getValueAt(TablaTipoTarea.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un TipoTarea", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
        controladorABMTipoTarea.abrirBaja(cod,this);
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        controladorABMTipoTarea.abrirAlta(this);
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void nomTipoTareaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomTipoTareaTextFieldKeyReleased
        nomfilTipoTarea=nomTipoTareaTextField.getText();
        List<DTOTipoTarea> listatipostarea = controladorABMTipoTarea.buscarTipoTarea(nomfilTipoTarea,"");  
        poblarTabla(listatipostarea); 
    }//GEN-LAST:event_nomTipoTareaTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMTipoTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonMod;
    private javax.swing.JTable TablaTipoTarea;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private javax.swing.JTextField nomTipoTareaTextField;
    // End of variables declaration//GEN-END:variables
}