package Main;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author FLIA HUDSON
 */
public class ABMTipoInstancia extends javax.swing.JFrame {
    ControladorABMTipoInstancia controladorABMTI = new ControladorABMTipoInstancia();
    List<DTOTipoInstancia> listatipoinstanciasordenadas;
    String filNombreTI;
    String filNombreSector;
    String filNombreTT;
    javax.swing.table.DefaultTableModel miTabla=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Tipo Instancia","Nombre Tipo Instancia", "Nombre Sector", "Fin Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    /**
     * Creates new form ABMTipoInstancia
     */
    public void setVisible(boolean b) {
        if (b==true) {
            List<DTOTipoInstancia> listatipoinstancias = controladorABMTI.buscarTipoInstancia(nomTipoInstanciaFieldText.getText(),nomSectorTextField.getText());
            poblarTabla(listatipoinstancias);
            super.setVisible(b);
        }
    }
    public void poblarTabla(List<DTOTipoInstancia> listatipoinstancias) {
        miTabla.setRowCount(0);
        listatipoinstanciasordenadas = ordenaTipoInstancia(listatipoinstancias);
        for (int i=0;i<listatipoinstanciasordenadas.size();i++)
            {
                DTOTipoInstancia unTipoInstancia = listatipoinstanciasordenadas.get(i);
                miTabla.addRow(new Object[]{unTipoInstancia.getCodTipoInstancia(),unTipoInstancia.getNombreTipoInstancia(),unTipoInstancia.getNombreSector(),unTipoInstancia.getFechaHoraFinVigenciaTipoInstancia()});
                TablaTipoInstancias.setAutoCreateRowSorter(true);
                TablaTipoInstancias.setModel(miTabla);
            }
    }
    private  List<DTOTipoInstancia> ordenaTipoInstancia(List<DTOTipoInstancia> listadtoTipoInstancias)
    {
        List<DTOTipoInstancia> ordenado,aux;
        ordenado=new ArrayList<DTOTipoInstancia>();
        aux= new ArrayList<DTOTipoInstancia>();
        for (int i=0; i< listadtoTipoInstancias.size();i++)
        {
            aux.add(listadtoTipoInstancias.get(i));
        }
        for (int i=0; i< listadtoTipoInstancias.size();i++)
        {
            int ultCod=0;
            DTOTipoInstancia saux=null;
            for(int j=0;j<aux.size();j++)
            {
                if(ultCod ==0)
                {
                    ultCod=aux.get(j).getCodTipoInstancia();
                    saux=aux.get(j);
                }
                if (ultCod >aux.get(j).getCodTipoInstancia())
                {
                    ultCod=aux.get(j).getCodTipoInstancia();
                    saux=aux.get(j);
                }
            }
            ordenado.add(saux);
            aux.remove(saux);
        }
         return ordenado; 
    }
    public ABMTipoInstancia() {
        initComponents();
        nomTipoInstanciaFieldText.setText("");
        nomSectorTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        nomSectorTextField = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        nomTipoInstanciaFieldText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTipoInstancias = new javax.swing.JTable();
        BotonAlta = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonMod = new javax.swing.JButton();
        verTareasButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM Tipo Instancia");

        label1.setText("Nombre Sector");

        nomSectorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomSectorTextFieldKeyReleased(evt);
            }
        });

        label3.setText("Nombre Tipo Instancia");

        nomTipoInstanciaFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTipoInstanciaFieldTextActionPerformed(evt);
            }
        });
        nomTipoInstanciaFieldText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomTipoInstanciaFieldTextKeyPressed(evt);
            }
        });

        TablaTipoInstancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Tipo Instancia", "Nombre Tipo Instancia", "Nombre Sector", "Fin Vigencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaTipoInstancias.setRowHeight(20);
        TablaTipoInstancias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(TablaTipoInstancias);

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });

        BotonMod.setText("Modificar");
        BotonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModActionPerformed(evt);
            }
        });

        verTareasButton.setText("Ver Tareas");
        verTareasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTareasButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verTareasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomTipoInstanciaFieldText)
                            .addComponent(nomSectorTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomTipoInstanciaFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomSectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMod)
                    .addComponent(verTareasButton)
                    .addComponent(BackButton)
                    .addComponent(BotonBaja)
                    .addComponent(BotonAlta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        controladorABMTI.abrirAlta(this);
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        Integer a;
        try  {
            a= (Integer) TablaTipoInstancias.getModel().getValueAt(TablaTipoInstancias.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un TipoInstancia", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
        controladorABMTI.abrirBaja(cod,this);
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModActionPerformed
        Integer a;
        try  {
              a= (Integer) TablaTipoInstancias.getModel().getValueAt(TablaTipoInstancias.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Sector", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
       controladorABMTI.abrirModificar(cod,this);
    }//GEN-LAST:event_BotonModActionPerformed

    private void verTareasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTareasButtonActionPerformed
        Integer a;
        try  {
            a= (Integer) TablaTipoInstancias.getValueAt(TablaTipoInstancias.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Tipo Instancia", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod = a;
        for (int j=0;j<listatipoinstanciasordenadas.size();j++)
            {
                DTOTipoInstancia untipoinstancia = listatipoinstanciasordenadas.get(j);
                if (cod==untipoinstancia.getCodTipoInstancia()) {
                    controladorABMTI.abrirConsultaTareas(untipoinstancia);
                } else {
                }
                    
            }
               
    }//GEN-LAST:event_verTareasButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void nomTipoInstanciaFieldTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomTipoInstanciaFieldTextKeyPressed
        filNombreTI = nomTipoInstanciaFieldText.getText();
        filNombreSector = nomSectorTextField.getText();
        List<DTOTipoInstancia> listatipoinstanciasfiltradas = controladorABMTI.buscarTipoInstancia(filNombreTI, filNombreSector);
        poblarTabla(listatipoinstanciasfiltradas);
    }//GEN-LAST:event_nomTipoInstanciaFieldTextKeyPressed

    private void nomSectorTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomSectorTextFieldKeyReleased
        filNombreTI = nomTipoInstanciaFieldText.getText();
        filNombreSector = nomSectorTextField.getText();
        List<DTOTipoInstancia> listatipoinstanciasfiltradas = controladorABMTI.buscarTipoInstancia(filNombreTI, filNombreSector);
        poblarTabla(listatipoinstanciasfiltradas);
    }//GEN-LAST:event_nomSectorTextFieldKeyReleased

    private void nomTipoInstanciaFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTipoInstanciaFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTipoInstanciaFieldTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMTipoInstancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonMod;
    private javax.swing.JTable TablaTipoInstancias;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private javax.swing.JTextField nomSectorTextField;
    private javax.swing.JTextField nomTipoInstanciaFieldText;
    private javax.swing.JButton verTareasButton;
    // End of variables declaration//GEN-END:variables
}
