package Main;
import java.util.*;
import Entidades.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.lang.*;
/**
 *
 * @author FLIA HUDSON
 */
public class ABMTipoTarea extends javax.swing.JFrame {
    ControladorABMTipoTarea controladorABMTipoTarea = new ControladorABMTipoTarea();
    List<DTOTipoTarea> listaTipoTareas;
    javax.swing.table.DefaultTableModel miTabla=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código TipoTarea", "Nombre TipoTarea", "Descripción", "Fecha Fin Vigencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        /**
     * Creates new form TipoTarea
     */
    public void setVisible(boolean b) {
        if (b==true) {
            List<DTOTipoTarea> listaTipoTareas = controladorABMTipoTarea.buscarTipoTarea();
            for (int i=0;i<listaTipoTareas.size();i++)
            {
                DTOTipoTarea unTipoTarea = listaTipoTareas.get(i);
                miTabla.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea(),unTipoTarea.getDescripcionTipoTarea(),unTipoTarea.getFechaFinVigenciaTipoTarea()});
                TablaTipoTarea.setModel(miTabla);
            }
        super.setVisible(b); 
        }
    }    
    public ABMTipoTarea() {
        initComponents();
        
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        codTipoTareaTextField = new javax.swing.JTextField();
        nomTipoTareaTextField = new javax.swing.JTextField();
        nomfilButton = new javax.swing.JButton();
        codfilButton = new javax.swing.JButton();
        BotonMod = new javax.swing.JButton();
        BotonBaja = new javax.swing.JButton();
        BotonAlta = new javax.swing.JButton();
        actualizarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTipoTarea = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Tipo Tarea");

        label1.setText("Nombre Tipo Tarea");

        label2.setText("Código Tipo Tarea");

        nomfilButton.setText("Filtrar");
        nomfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfilButtonActionPerformed(evt);
            }
        });

        codfilButton.setText("Filtrar");
        codfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codfilButtonActionPerformed(evt);
            }
        });

        BotonMod.setText("Modificar");
        BotonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModActionPerformed(evt);
            }
        });

        BotonBaja.setText("Baja");
        BotonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBajaActionPerformed(evt);
            }
        });

        BotonAlta.setText("Alta");
        BotonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaActionPerformed(evt);
            }
        });

        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        TablaTipoTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código TipoTarea", "Nombre Tipo Tarea", "Descripción", "Fin Vigencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaTipoTarea.setRowHeight(20);
        TablaTipoTarea.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(TablaTipoTarea);
        if (TablaTipoTarea.getColumnModel().getColumnCount() > 0) {
            TablaTipoTarea.getColumnModel().getColumn(0).setMinWidth(0);
            TablaTipoTarea.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackButton.setText("Volver");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(actualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomTipoTareaTextField)
                            .addComponent(codTipoTareaTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomfilButton)
                        .addComponent(nomTipoTareaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codfilButton)
                    .addComponent(codTipoTareaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarButton)
                    .addComponent(BotonAlta)
                    .addComponent(BotonBaja)
                    .addComponent(BotonMod)
                    .addComponent(BackButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfilButtonActionPerformed
        String nomfilTipoTarea;
        nomfilTipoTarea =nomTipoTareaTextField.getText();
        //Limpio la tabla
        miTabla.setRowCount(0);
        List<DTOTipoTarea> listaTipoTareas = controladorABMTipoTarea.buscarTipoTarea(nomfilTipoTarea);
        for (int j=0;j<listaTipoTareas.size();j++)
        {
            DTOTipoTarea unTipoTarea = listaTipoTareas.get(j);

            miTabla.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea(),unTipoTarea.getDescripcionTipoTarea(),unTipoTarea.getFechaFinVigenciaTipoTarea()});

        }
        TablaTipoTarea.setModel(miTabla);
    }//GEN-LAST:event_nomfilButtonActionPerformed

    private void codfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codfilButtonActionPerformed
        int codfilTipoTarea;
        if ("".equals(codTipoTareaTextField.getText()) ){
            List<DTOTipoTarea> listaTipoTareas = controladorABMTipoTarea.buscarTipoTarea();
            miTabla.setRowCount(0);

            for (int j=0;j<listaTipoTareas.size();j++)
            {
                DTOTipoTarea unTipoTarea = listaTipoTareas.get(j);

                miTabla.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea(),unTipoTarea.getDescripcionTipoTarea(),unTipoTarea.getFechaFinVigenciaTipoTarea()});

            }

            TablaTipoTarea.setModel(miTabla);
        }
        else {
            codfilTipoTarea = Integer.parseInt(codTipoTareaTextField.getText());
            //Limpio la tabla
            miTabla.setRowCount(0);
            List<DTOTipoTarea> listaTipoTareas = controladorABMTipoTarea.buscarTipoTarea(codfilTipoTarea);

            for (int j=0;j<listaTipoTareas.size();j++)
            {
                DTOTipoTarea unTipoTarea = listaTipoTareas.get(j);

                miTabla.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea(),unTipoTarea.getDescripcionTipoTarea(),unTipoTarea.getFechaFinVigenciaTipoTarea()});

            }

            TablaTipoTarea.setModel(miTabla);
        }
    }//GEN-LAST:event_codfilButtonActionPerformed

    private void BotonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModActionPerformed
        Integer a;
        try  {
            a= (Integer) TablaTipoTarea.getModel().getValueAt(TablaTipoTarea.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un TipoTarea", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
        controladorABMTipoTarea.abrirModificar(cod);
        // System.out.print(cod);
    }//GEN-LAST:event_BotonModActionPerformed

    private void BotonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBajaActionPerformed
        Integer a;
        try  {
            a= (Integer) TablaTipoTarea.getModel().getValueAt(TablaTipoTarea.getSelectedRow(), 0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un TipoTarea", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int cod=a;
        controladorABMTipoTarea.abrirBaja(cod);
    }//GEN-LAST:event_BotonBajaActionPerformed

    private void BotonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaActionPerformed
        controladorABMTipoTarea.abrirAlta();
    }//GEN-LAST:event_BotonAltaActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        miTabla.setRowCount(0);
        setVisible(true);
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMTipoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMTipoTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotonAlta;
    private javax.swing.JButton BotonBaja;
    private javax.swing.JButton BotonMod;
    private javax.swing.JTable TablaTipoTarea;
    private javax.swing.JButton actualizarButton;
    private javax.swing.JTextField codTipoTareaTextField;
    private javax.swing.JButton codfilButton;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField nomTipoTareaTextField;
    private javax.swing.JButton nomfilButton;
    // End of variables declaration//GEN-END:variables
}