package Main;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author FLIA HUDSON
 */
public class AltaTipoInstancia extends javax.swing.JFrame {
    ControladorABMTipoInstancia controladorABMTI;
    DTOTipoInstancia dtoalta = new DTOTipoInstancia();
    List<DTOTipoTarea> listatipostarea;
    List<DTOTipoTarea> listaTiposTareaParaAlta;
    List<DTOSector> listasectores;
    javax.swing.table.DefaultTableModel miTablaDisponibles=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código TT","Nombre Tipo Tarea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    javax.swing.table.DefaultTableModel miTablaElegidas=new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código TT","Nombre Tipo Tarea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    /*NO SIRVEN
    DefaultListModel milista = new DefaultListModel();
    DefaultListModel milista2 = new DefaultListModel();
    */  
    public AltaTipoInstancia() {
        initComponents();
    }
    public void setVisible(boolean b) {
        
        listasectores = controladorABMTI.buscarSectoresVigentes();
        for (int i=0;i<listasectores.size();i++)
        {
            DTOSector unSector = listasectores.get(i);
            sectoresComboBox.addItem(unSector);
        }
        listatipostarea = controladorABMTI.buscarTiposTareaVigentes();
        for (int i=0;i<listatipostarea.size();i++)
        {
            DTOTipoTarea unTipoTarea = listatipostarea.get(i);
            miTablaDisponibles.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea()});
            TiposTareaVigentesTable.setModel(miTablaDisponibles);
        }
        super.setVisible(b);
    }
    public void inicializaAlta(ControladorABMTipoInstancia cont){
       controladorABMTI=cont;
       listaTiposTareaParaAlta = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removerTareaButtonold = new javax.swing.JButton();
        agregarTareaButtonold = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTareasElegidas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTareasVigentes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codaltaTipoInstanciaTextField = new javax.swing.JTextField();
        nomaltaTipoInstanciaTextField = new javax.swing.JTextField();
        sectoresComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        altaTipoInstanciaButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TiposTareaVigentesTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TiposTareaElegidasTable = new javax.swing.JTable();
        agregarTareaButton = new javax.swing.JButton();
        removerTareaButton = new javax.swing.JButton();

        removerTareaButtonold.setText("<--");
        removerTareaButtonold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTareaButtonoldActionPerformed(evt);
            }
        });

        agregarTareaButtonold.setText("-->");
        agregarTareaButtonold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTareaButtonoldActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaTareasElegidas);

        jScrollPane1.setViewportView(listaTareasVigentes);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta Tipo Instancia");

        jLabel1.setText("Código Tipo Instancia:");

        jLabel2.setText("Nombre Tipo Instancia:");

        jLabel3.setText("Sector Tipo Instancia");

        codaltaTipoInstanciaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codaltaTipoInstanciaTextFieldActionPerformed(evt);
            }
        });

        nomaltaTipoInstanciaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomaltaTipoInstanciaTextFieldActionPerformed(evt);
            }
        });

        sectoresComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectoresComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Elija los Tipos de Tarea vigentes que pertenecerán al Tipo Instancia");

        altaTipoInstanciaButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        altaTipoInstanciaButton.setText("Dar alta al Tipo Instancia");
        altaTipoInstanciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaTipoInstanciaButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        TiposTareaVigentesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo TT", "Nombre Tipo Tarea"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TiposTareaVigentesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TiposTareaVigentesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TiposTareaVigentesTable);
        TiposTareaVigentesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TiposTareaVigentesTable.getColumnModel().getColumnCount() > 0) {
            TiposTareaVigentesTable.getColumnModel().getColumn(0).setMinWidth(0);
            TiposTareaVigentesTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        TiposTareaElegidasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo TT", "Nombre Tipo Tarea"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TiposTareaElegidasTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TiposTareaElegidasTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TiposTareaElegidasTable);
        TiposTareaElegidasTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TiposTareaElegidasTable.getColumnModel().getColumnCount() > 0) {
            TiposTareaElegidasTable.getColumnModel().getColumn(0).setMinWidth(0);
            TiposTareaElegidasTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        agregarTareaButton.setText("-->");
        agregarTareaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTareaButtonActionPerformed(evt);
            }
        });

        removerTareaButton.setText("<--");
        removerTareaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTareaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(altaTipoInstanciaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomaltaTipoInstanciaTextField)
                                    .addComponent(codaltaTipoInstanciaTextField)
                                    .addComponent(sectoresComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agregarTareaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(removerTareaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codaltaTipoInstanciaTextField)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomaltaTipoInstanciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sectoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(agregarTareaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removerTareaButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altaTipoInstanciaButton)
                    .addComponent(cancelarButton)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codaltaTipoInstanciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codaltaTipoInstanciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codaltaTipoInstanciaTextFieldActionPerformed

    private void nomaltaTipoInstanciaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomaltaTipoInstanciaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomaltaTipoInstanciaTextFieldActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        setVisible(false);
        dispose(); 
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void sectoresComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectoresComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectoresComboBoxActionPerformed

    private void altaTipoInstanciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaTipoInstanciaButtonActionPerformed
        try  {
            dtoalta.setCodTipoInstancia(Integer.parseInt(codaltaTipoInstanciaTextField.getText()));
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al ingresar codSector. Por favor ingrese un número", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dtoalta.setNombreTipoInstancia(nomaltaTipoInstanciaTextField.getText());
        dtoalta.setDTOSector((DTOSector)sectoresComboBox.getSelectedItem());
        dtoalta.setListaTipoTarea(listaTiposTareaParaAlta);
        controladorABMTI.darAltaTipoInstancia(dtoalta);
        return;       
    }//GEN-LAST:event_altaTipoInstanciaButtonActionPerformed

    private void removerTareaButtonoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTareaButtonoldActionPerformed
        /*
        List<String> listaseleccionadas = listaTareasElegidas.getSelectedValuesList();
        for (int i=0;i<listaseleccionadas.size();i++)
        {
            int posicionfincodigo = listaseleccionadas.get(i).lastIndexOf(")", 0);
            int codigo = Integer.parseInt(listaseleccionadas.get(i).substring(1, posicionfincodigo));
            for (int j=0;i<listatipostarea.size();i++){
                DTOTipoTarea untipotarea = listatipostarea.get(j);
                if (codigo==untipotarea.getCodTipoTarea()) {
                    milista2.removeElement(listaseleccionadas.get(i));
                    listaTiposTareaParaAlta.remove(untipotarea);
                }
            }
        }
        listaTareasElegidas.setModel(milista2);
        */
    }//GEN-LAST:event_removerTareaButtonoldActionPerformed

    private void agregarTareaButtonoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTareaButtonoldActionPerformed
        /* VIEJO      
        List<String> listaseleccionadas = TiposTareaVigentesTable.getSelectedValuesList();
        for (int i=0;i<listaseleccionadas.size();i++)
        {
            int posicionfincodigo = listaseleccionadas.get(i).indexOf("]", 0);
            int codigo = Integer.parseInt(listaseleccionadas.get(i).substring(1, posicionfincodigo));
            for (int j=0;i<listatipostarea.size();i++){
                DTOTipoTarea untipotarea = listatipostarea.get(j);
                if (codigo==untipotarea.getCodTipoTarea()) {
                    milista2.addElement(listaseleccionadas.get(i));
                    listaTiposTareaParaAlta.add(untipotarea);
                }
            }
        }
        listaTareasElegidas.setModel(milista2);
        */
    }//GEN-LAST:event_agregarTareaButtonoldActionPerformed

    private void agregarTareaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTareaButtonActionPerformed
        int a;
        try {
            a= (Integer) TiposTareaVigentesTable.getModel().getValueAt(TiposTareaVigentesTable.getSelectedRow(), 0);
            }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Tipo de Tarea para asignar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int i=0;i<listatipostarea.size();i++)
        {
            DTOTipoTarea unTipoTarea = listatipostarea.get(i);
            if (a==unTipoTarea.getCodTipoTarea())
            {
                miTablaElegidas.addRow(new Object[]{unTipoTarea.getCodTipoTarea(),unTipoTarea.getNombreTipoTarea()});
                TiposTareaElegidasTable.setModel(miTablaElegidas);
                listaTiposTareaParaAlta.add(unTipoTarea);
                return;
            }
        }
    }//GEN-LAST:event_agregarTareaButtonActionPerformed

    private void removerTareaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTareaButtonActionPerformed
        int a;
        try  {
              a= (Integer) TiposTareaElegidasTable.getModel().getValueAt(TiposTareaElegidasTable.getSelectedRow(), 0);
             }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Seleccione un Tipo de Tarea asignada", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        miTablaElegidas.removeRow(TiposTareaElegidasTable.getSelectedRow());
        for (int i=0;i<listatipostarea.size();i++)
        {
            DTOTipoTarea unTipoTarea = listatipostarea.get(i);
            if (a==unTipoTarea.getCodTipoTarea())
            {
                TiposTareaElegidasTable.setModel(miTablaElegidas);
                listaTiposTareaParaAlta.remove(unTipoTarea);
            }
        }
        System.out.println("!");
    }//GEN-LAST:event_removerTareaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaTipoInstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaTipoInstancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TiposTareaElegidasTable;
    private javax.swing.JTable TiposTareaVigentesTable;
    private javax.swing.JButton agregarTareaButton;
    private javax.swing.JButton agregarTareaButtonold;
    private javax.swing.JButton altaTipoInstanciaButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField codaltaTipoInstanciaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaTareasElegidas;
    private javax.swing.JList<String> listaTareasVigentes;
    private javax.swing.JTextField nomaltaTipoInstanciaTextField;
    private javax.swing.JButton removerTareaButton;
    private javax.swing.JButton removerTareaButtonold;
    private javax.swing.JComboBox<DTOSector> sectoresComboBox;
    // End of variables declaration//GEN-END:variables
}
